services:

  mssql:
    container_name: clinic-sql-server
    image: mcr.microsoft.com/mssql/server:2022-latest
    restart: unless-stopped
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "0bd7903b-f568-4894-8d72-3c1b507e5644"
    volumes:
      - my-volume:/var/opt/mssql
    ports:
      - "1433:1433"
          
  

  proxy:
    container_name: clinic_proxy_container
    image: nginx:mainline
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    restart: unless-stopped
    ports:
      - "80:80"

  authorization.api:
    image: authorization.api
    build:
      context: .
      dockerfile: Authorization.Api/Dockerfile
    restart: unless-stopped
    ports:
      - "8081:8080"
  
 
  redis:
    image: redis
    ports:
      - "6379:6379"

  clinic-mq:
    image: rabbitmq:management
    container_name: Clinic.RabbitMq
    hostname: clinic-mq
    ports:
      - 15672:15672
      - 5671:5671
    volumes:
        - ~/.container/queue/data/:/var/lib/rabbitmq/
        - ~/.container/queue/log/:/var/log/rabbitmq
    environment:
        RABBITMQ_DEFAULT_USER: guest
        RABBITMQ_DEFAULT_PASS: guest

volumes:
  my-volume: